Repository croct-tech/template-ui-js, pull requests merged in 2025-04, with the labels that each got.

#14 Fix package publishing
  .github/workflows/deploy-published-releases-cdn.yaml
  .github/workflows/deploy-published-releases-npm.yaml
Labels: maintenance

#16 Configure new workflow permissions
  .github/workflows/deploy-published-releases-cdn.yaml
Labels: maintenance

#17 Fix subbrand line height
  src/react/TemplateCanvas/styles.module.css
Labels: maintenance

#19 Add extension to import
  .eslintrc.cjs
  src/next/TemplateCanvas/index.tsx
Labels: bug

#20 Add support for specifying target
  src/react/LinkButton/LinkButton.stories.tsx
  src/react/LinkButton/index.tsx
Labels: feature

#21 Add CTA target to template canvas
  package-lock.json
  src/next/TemplateCanvas/TemplateCanvas.stories.tsx
  src/react/TemplateCanvas/TemplateCanvas.stories.tsx
  src/react/TemplateCanvas/index.tsx
  src/web/TemplateCanvas/TemplateCanvas.stories.ts
  src/web/TemplateCanvas/index.tsx
Labels: feature
